[package]
name = "frustal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.2"
inline-python = "0.7.1"
rayon = "1.5.1"